import os
import sys
import subprocess
import shutil
import re

def get_current_macs():
    """Returns a list of MAC addresses on the current machine."""
    macs = set()
    try:
        # Run getmac command
        cmd = "getmac /v /fo csv"
        result = subprocess.check_output(cmd, shell=True).decode('cp949', errors='ignore')
        
        # Parse output for MAC addresses
        # Regex to find MACs: XX-XX-XX-XX-XX-XX or XX:XX:XX:XX:XX:XX
        found = re.findall(r'([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})', result)
        
        # re.findall with groups returns tuples, we need to extract the full match
        # Better regex for full match extraction
        iterator = re.finditer(r'((?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2})', result)
        for match in iterator:
            macs.add(match.group(1).upper().replace(':', '-'))
            
    except Exception as e:
        print(f"Warning: Could not retrieve current MACs: {e}")
    
    return list(macs)

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(base_dir)

    print("=== Secure Build Process Started ===")
    
    # 1. Show Current Machine MACs (Convenience)
    current_macs = get_current_macs()
    print("\n[INFO] Current Machine MAC Addresses:")
    for m in current_macs:
        print(f"  - {m}")
    print("If you want to run the bot on THIS machine, make sure one of these is in the list.\n")

    # 2. Read MAC List
    allowed_list_path = "허용된_MAC주소_목록.txt"
    macs = []
    if os.path.exists(allowed_list_path):
        with open(allowed_list_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"): continue
                macs.append(line.upper().replace(':', '-')) # Normalize
    else:
        print(f"[WARNING] {allowed_list_path} not found. Creating empty one.")
        with open(allowed_list_path, "w", encoding="utf-8") as f:
            f.write("# Enter MAC addresses here (one per line)\n")
    
    print(f"[INFO] Found {len(macs)} allowed MAC addresses.")
    
    # 3. Write mac_config.py
    with open("mac_config.py", "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by build_secure.py\n")
        f.write(f"ALLOWED_MACS = {repr(macs)}\n")
    
    print("[INFO] mac_config.py updated.")

    # Helper for robust cleanup
    def force_clean(path):
        if os.path.exists(path):
            print(f"Cleaning {path}...")
            # Try shutil first
            try:
                shutil.rmtree(path, ignore_errors=True)
            except:
                pass
            # If still exists, use Windows command (more robust)
            if os.path.exists(path):
                subprocess.run(f'rmdir /s /q "{path}"', shell=True, stderr=subprocess.DEVNULL)
            
            # Double check
            if os.path.exists(path):
                print(f"Warning: Could not fully clean {path}. Build might fail.")
                import time
                time.sleep(1)

    # 4. Run PyInstaller
    print("\n[INFO] Running PyInstaller...")
    
    # Clean build and dist folders manually
    force_clean(os.path.join(base_dir, "build", "NaverShoppingBot_Corp"))
    force_clean(os.path.join(base_dir, "dist", "NaverShoppingBot_Corp"))

    try:
        # Removed --clean to prevent PyInstaller's internal cleanup from crashing (we did it manually)
        subprocess.check_call([sys.executable, "-m", "PyInstaller", "NaverShoppingBot_Corp.spec", "--noconfirm"])
    except subprocess.CalledProcessError:
        print("\n[ERROR] Build Failed!")
        sys.exit(1)

    # 5. Copy to Target Directory
    target_dir = r"최종ver\회사용\NaverShoppingBot_Corp"
    source_dir = r"dist\NaverShoppingBot_Corp"
    
    print(f"\n[INFO] Copying files to {target_dir}...")
    # Use robust force_clean instead of shutil.rmtree
    force_clean(target_dir)
    
    shutil.copytree(source_dir, target_dir, dirs_exist_ok=True)
    
    # Copy the Guide and List for reference (Optional, maybe not list for security? No, list stays with builder)
    shutil.copy("보안설정_가이드.txt", os.path.join(os.path.dirname(target_dir), "보안설정_가이드.txt"))

    print("\n=== Build Complete Successfully! ===")
    print(f"Output Location: {os.path.abspath(target_dir)}")

if __name__ == "__main__":
    main()
